language: python
python:
        - 2.7
install:
        - pushd __root__
        - python setup.py saveopts --filename=setup.cfg pkg_prepare
          --ra-metadata-dir=$(pwd)/cluster
          --ccs-flatten=${HOME}/ccs_flatten
        - pip install -e .
        - popd
script: ./run-tests -d
