language: python
python:
        - 2.6
        # cf. https://github.com/travis-ci/travis-ci/issues/2219
        - "2.7_with_system_site_packages"
before_install:
        # speed the run up
        - python -c
          'from sys import exit, version_info as v; exit(v[:2] in ((2, 7), (3, 2)))'
          || sudo apt-get install -qq python-lxml python-distribute
install:
        - cd __root__
        - python setup.py -q saveopts -f setup.cfg pkg_prepare
                             --ra-metadata-dir="$(pwd)/cluster"
                             --ccs-flatten="$(dirname $(pwd))/ccs_flatten"
        #- cat setup.cfg
        - pip install -qe .[test]
          || { ret=$?; cat ~/.pip/pip.log; f() { return $1; }; f $ret; }

script: ./run-tests
