language: python
python:
        - 2.6
        # cf. https://github.com/travis-ci/travis-ci/issues/2219
        - "2.7_with_system_site_packages"
before_install:
        # http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages
        # https://github.com/travis-ci/travis-ci/issues/2124#issuecomment-38992012
        - sudo apt-get update -qq
        # speed the run up
        - python -c
          'from sys import exit, version_info as v; exit(v[:2] in ((2, 7), (3, 2)))'
          || sudo apt-get install -qq python-lxml python-distribute
install:
        - cd __root__
        - python setup.py -q saveopts -f setup.cfg pkg_prepare
                             --ra-metadata-dir="$(pwd)/cluster"
                             --ccs-flatten="$(dirname $(pwd))/ccs_flatten"
                             --editor="sed -i 's|\(force-block=\"\)false|\1true|;w /dev/stdout"
        #- cat setup.cfg
        # make following robust enough to deal with pip pre-6.0(?)
        - true;{
               pip install --disable-pip-version-check -- pip >/dev/null
               && pip install --disable-pip-version-check -qe .[test];
          } || {
               pip install --disable-pip-version-check -- pip 2>/dev/null >&2
               || pip install -qe .[test];
          } || {
               ret=$?;
               echo "LOGS>"; cat ~/.pip/pip.log ~/.cache/pip/log/debug.log 2>/dev/null;
               f() { return $1; }; f $ret;
          }

script: ./run-tests
